// ================================================================
// CURRICULUM — every section of every module, in study order.
// week: plan week (1–5 new content, 6 = consolidation)
// stream: A = Stats (Prob → MAS2901), B = Pure (LA → CA), C = Applied (VC → DE)
// pick: I = Implement (quick win), C = Challenge (hard, essential),
//       P = Possible (skim), K = Kill (skip — non-examinable / low payoff)
// src: where to read it. key: key points shown in Present / Fix steps.
// ================================================================
const PLAN_START = '2026-10-01';   // Week 1, day 1
const PLAN_WEEKS = 6;
const PASS_MARK = 0.8;

const STATS_URL = 'https://matthewalexanderfisher.github.io/NCL-MAS2901/content/main/';

const MODULES = {
  PROB: {code:'MAS2909', name:'Probability',                 short:'Prob',  stream:'A', color:'#F472B6'},
  STAT: {code:'MAS2901', name:'Statistical Inference',       short:'Stats', stream:'A', color:'#FB7185'},
  LA:   {code:'MAS2701', name:'Linear Algebra',              short:'LA',    stream:'B', color:'#60A5FA'},
  CA:   {code:'MAS2702', name:'Complex Analysis',            short:'CA',    stream:'B', color:'#A78BFA'},
  VC:   {code:'MSP2801', name:'Vector Calculus',             short:'VC',    stream:'C', color:'#34D399'},
  DE:   {code:'MSP2802', name:'Differential Equations, Waves & Transforms', short:'DE', stream:'C', color:'#FBBF24'},
};

const STREAMS = {A:'Stats', B:'Pure', C:'Applied'};

const SECTIONS = [
// ---------------------------------------------------------------- STREAM A
// Week 1
{id:'prob-1-events', mod:'PROB', week:1, pick:'I', title:'Probability, conditioning & Bayes',
 src:'Prob notes: Recap Ch1 §1.1 · Stats notes Ch1 "Probability and Events"', url:STATS_URL+'part1/1-prob-theory.html',
 key:['A probability space is (Ω, 𝓕, P): sample space, collection of events, probability measure satisfying 0≤P(A)≤1, P(Ω)=1 and countable additivity for disjoint events.',
      'Inclusion–exclusion: P(A∪B) = P(A)+P(B)−P(A∩B).',
      'Conditional probability: P(A|B) = P(A∩B)/P(B), for P(B)>0.',
      'Law of total probability: for a partition B₁,…,Bₙ, P(A) = Σ P(A|Bᵢ)P(Bᵢ).',
      'Bayes: P(B|A) = P(A|B)P(B) / [P(A|B)P(B) + P(A|Bᶜ)P(Bᶜ)].',
      'Independent: P(A∩B)=P(A)P(B). Mutually exclusive (A∩B=∅) is a different idea — disjoint events with positive probability are never independent.']},
{id:'prob-1-rvs', mod:'PROB', week:1, pick:'I', title:'Random variables: pmf, pdf and cdf',
 src:'Prob notes: Recap Ch1 §1.2 · Stats notes Ch1 "Random Variables"', url:STATS_URL+'part1/1-prob-theory.html#sec-random-variables',
 key:['A random variable is a function X: Ω → ℝ.',
      'Discrete: pmf p(k)=P(X=k) with p(k)≥0 and Σp(k)=1.',
      'cdf F(s)=P(X≤s): increasing, F(−∞)=0, F(∞)=1; a step function for discrete X.',
      'Continuous: F(s)=∫_{−∞}^{s} f(x)dx and f = F′. A density is not a probability — f(x) can exceed 1.',
      'P(a<X≤b) = F(b)−F(a).']},
{id:'prob-1-moments', mod:'PROB', week:1, pick:'I', title:'Expectation, variance & covariance',
 src:'Prob notes: Recap Ch1 §1.3 · Stats notes Ch1 "Expectations, Variances and Covariances"', url:STATS_URL+'part1/1-prob-theory.html',
 key:['E(X)=Σ k P(X=k) or ∫ x f(x)dx; E[g(X)] = Σ g(k)P(X=k) or ∫ g(x)f(x)dx (no need for the distribution of g(X)).',
      'Var(X) = E[(X−μ)²] = E(X²) − (E X)².',
      'E(aX+b) = aE(X)+b and Var(aX+b) = a²Var(X).',
      'Cov(X,Y) = E(XY) − E(X)E(Y); Corr = Cov/(σ_X σ_Y) ∈ [−1,1].',
      'Independent ⇒ Cov = 0, but Cov = 0 does NOT imply independence.',
      'Var(X+Y) = Var X + Var Y + 2Cov(X,Y).']},
{id:'prob-1-dists', mod:'PROB', week:1, pick:'I', title:'Common distributions & MGFs',
 src:'Prob notes: Recap Ch1 §1.4 and §1.4.1', url:null,
 key:['Bernoulli(p): mean p, var p(1−p). Binomial(n,p): mean np, var np(1−p).',
      'Poisson(λ): mean = var = λ. Exponential(λ): mean 1/λ, var 1/λ², cdf 1−e^{−λx}.',
      'Uniform(a,b): mean (a+b)/2, var (b−a)²/12. Normal(μ,σ²): mean μ, var σ².',
      'Gamma(k,θ) (shape–scale): mean kθ, var kθ². Beta(α,β): mean α/(α+β). χ²_k: mean k, var 2k. Cauchy: no mean.',
      'MGF M_X(t) = E[e^{tX}]; M_X^{(n)}(0) = E(Xⁿ). Poisson(λ): M(t) = exp(λ(eᵗ−1)).',
      'For independent X, Y, the MGF of X + Y is M_X(t)·M_Y(t).']},
{id:'stat-2', mod:'STAT', week:1, pick:'I', title:'What is statistical inference?',
 src:'Stats notes Ch2', url:STATS_URL+'part1/2-what-is-stats-inference.html',
 key:['Inference is "inverse probability": observe data x̲, learn about the unknown parameter θ of the population distribution.',
      'Random sample X₁,…,Xₙ (random, before observation) vs observed data x₁,…,xₙ (fixed numbers).',
      'A random sample means X₁,…,Xₙ iid ~ Distribution(θ). "Random sample" ≠ representative: selection bias can break the model.',
      'A statistical model is a family of distributions indexed by θ ∈ Θ (the parameter space). E.g. N(μ,σ²): Θ = ℝ×(0,∞).',
      'Parameter (population feature, e.g. p, μ) ≠ statistic (computed from the sample, e.g. X̄).',
      'Data types: univariate/multivariate; continuous, discrete (counts), categorical nominal/ordinal.']},
{id:'stat-3', mod:'STAT', week:1, pick:'I', title:'Types of inference',
 src:'Stats notes Ch3', url:STATS_URL+'part1/3-types-of-inference.html',
 key:['Frequentist: θ fixed but unknown; probability describes data/procedures under repeated sampling.',
      'Bayesian: uncertainty about θ described by a prior π(θ), updated to a posterior π(θ | data).',
      'A 95% confidence interval: the PROCEDURE covers the fixed θ in 95% of repeated samples.',
      'A 95% credible interval: P(θ ∈ [L,U] | data) = 0.95.',
      'Tasks: point estimation, interval estimation, hypothesis testing (examined); prediction (not examined).',
      'Failing to reject H₀ does not prove H₀ is true.']},
// Week 2
{id:'prob-2-joint', mod:'PROB', week:2, pick:'I', title:'Random vectors, joint & marginal distributions', src:'Prob notes Ch2 §2.1–2.3', url:null, key:[]},
{id:'prob-2-cond', mod:'PROB', week:2, pick:'C', title:'Conditional distributions & conditional expectation', src:'Prob notes Ch2 §2.4–2.5', url:null, key:[]},
{id:'prob-2-cov', mod:'PROB', week:2, pick:'I', title:'Independence, covariance, mean vector & covariance matrix', src:'Prob notes Ch2 §2.6–2.9', url:null, key:[]},
{id:'prob-2-mvn', mod:'PROB', week:2, pick:'C', title:'Multivariate normal distribution', src:'Prob notes Ch2 §2.10–2.11', url:null, key:[]},
{id:'prob-3-trans', mod:'PROB', week:2, pick:'C', title:'Transformations of random variables & vectors (Jacobian)', src:'Prob notes Ch3 §3.1.1–3.1.2', url:null, key:[]},
{id:'prob-3-sums', mod:'PROB', week:2, pick:'C', title:'Sums, differences, products, quotients; convolution', src:'Prob notes Ch3 §3.1.3–3.1.6', url:null, key:[]},
// Week 3
{id:'prob-4-tail', mod:'PROB', week:3, pick:'I', title:'Tail bounds (Markov, Chebyshev)', src:'Prob notes Ch4 §4.1', url:null, key:[]},
{id:'prob-4-modes', mod:'PROB', week:3, pick:'C', title:'Modes of convergence & how they relate', src:'Prob notes Ch4 §4.2–4.3', url:null, key:[]},
{id:'prob-4-limits', mod:'PROB', week:3, pick:'C', title:'Law of Large Numbers & Central Limit Theorem', src:'Prob notes Ch4 §4.4–4.6', url:null, key:[]},
{id:'stat-4-est', mod:'STAT', week:3, pick:'I', title:'Estimators vs estimates; bias & MSE', src:'Stats notes Ch4', url:STATS_URL+'part2/4-freq-point-estimation.html#sec-estimator-properties', key:[]},
{id:'stat-4-asym', mod:'STAT', week:3, pick:'C', title:'CLT & asymptotic properties of estimators', src:'Stats notes Ch4', url:STATS_URL+'part2/4-freq-point-estimation.html#sec-clt', key:[]},
// Week 4
{id:'stat-5-mle', mod:'STAT', week:4, pick:'C', title:'Likelihood & maximum likelihood estimation', src:'Stats notes Ch5', url:STATS_URL+'part2/5-likelihood.html', key:[]},
{id:'stat-5-info', mod:'STAT', week:4, pick:'C', title:'Fisher information, efficiency & Cramér–Rao', src:'Stats notes Ch5', url:STATS_URL+'part2/5-likelihood.html', key:[]},
{id:'stat-5-asym', mod:'STAT', week:4, pick:'C', title:'Asymptotic distribution of the MLE', src:'Stats notes Ch5', url:STATS_URL+'part2/5-likelihood.html', key:[]},
{id:'stat-6-bayes', mod:'STAT', week:4, pick:'I', title:'Bayes’ theorem for densities & conjugate priors', src:'Stats notes Ch6', url:STATS_URL+'part2/6-bayes-inference.html', key:[]},
{id:'stat-6-est', mod:'STAT', week:4, pick:'C', title:'Bayesian estimators & asymptotic posterior', src:'Stats notes Ch6', url:STATS_URL+'part2/6-bayes-inference.html', key:[]},
// Week 5
{id:'stat-7-ci', mod:'STAT', week:5, pick:'I', title:'Confidence intervals: definition & interpretation', src:'Stats notes Ch7', url:STATS_URL+'part3/7-freq-interval-estimation.html#sec-interpreting-ci', key:[]},
{id:'stat-7-exact', mod:'STAT', week:5, pick:'C', title:'Exact & approximate confidence intervals', src:'Stats notes Ch7', url:STATS_URL+'part3/7-freq-interval-estimation.html#sec-exact-ci', key:[]},
{id:'stat-8-cred', mod:'STAT', week:5, pick:'I', title:'Credible intervals', src:'Stats notes Ch8', url:STATS_URL+'part3/8-bayes-interval-estimation.html', key:[]},
{id:'stat-8-hdi', mod:'STAT', week:5, pick:'P', title:'Highest density intervals', src:'Stats notes Ch8', url:STATS_URL+'part3/8-bayes-interval-estimation.html', key:[]},
{id:'stat-9-proc', mod:'STAT', week:5, pick:'I', title:'The hypothesis testing procedure', src:'Stats notes Ch9', url:STATS_URL+'part4/9-freq-hypothesis-testing.html#sec-testing-procedure', key:[]},
{id:'stat-9-tests', mod:'STAT', week:5, pick:'C', title:'Examinable hypothesis tests', src:'Stats notes Ch9', url:STATS_URL+'part4/9-freq-hypothesis-testing.html', key:[]},
{id:'stat-9-nonexam', mod:'STAT', week:5, pick:'K', title:'Non-examinable hypothesis tests', src:'Stats notes Ch9', url:null, key:[]},
{id:'stat-10', mod:'STAT', week:5, pick:'K', title:'Bayesian hypothesis testing (not examinable)', src:'Stats notes Ch10', url:null, key:[]},
{id:'prob-extra', mod:'PROB', week:5, pick:'K', title:'Non-examinable extras (multinomial, characteristic functions)', src:'Prob notes: Non-examinable chapter', url:null, key:[]},

// ---------------------------------------------------------------- STREAM B
// Week 1 — Linear Algebra
{id:'la-1.1', mod:'LA', week:1, pick:'I', title:'Fields', src:'LA notes §1.1 (PDF p.3–4)', url:null,
 key:['A field F has + and · that are commutative, associative, distributive, with 0 and 1, additive inverses, and multiplicative inverses for every NONZERO element.',
      'Fields: ℚ, ℝ, ℂ, and ℤ_p for p prime.',
      'Not fields: ℕ (no 0/additive inverses/reciprocals), ℤ (2 has no inverse), Matₙₓₙ (not commutative; non-invertible nonzero matrices).']},
{id:'la-1.2', mod:'LA', week:1, pick:'I', title:'Vector spaces', src:'LA notes §1.2 (PDF p.4–8)', url:null,
 key:['A vector space over F: a set V with vector addition and scalar multiplication satisfying 8 axioms (commutativity, associativity, zero vector, additive inverses, 1•u=u, α•(β•u)=(αβ)•u, two distributive laws).',
      'Standard examples: Fⁿ, Matₘₓₙ(F), F[x] (polynomials), F^∞ (sequences), functions ℝ→ℝ.',
      'Consequences: 0 is unique, inverses are unique, 0•u = 0, λ•0 = 0, (−1)•u = −u.']},
{id:'la-1.3', mod:'LA', week:1, pick:'I', title:'Subspaces', src:'LA notes §1.3 (PDF p.9–11)', url:null,
 key:['Subspace test: a NONEMPTY W ⊆ V is a subspace iff it is closed under addition and under scalar multiplication.',
      'Quick check: a subspace must contain 0. If 0 ∉ W it is not a subspace (but 0 ∈ W alone is not enough).',
      'Examples: {0} and V (trivial), ℝₙ[x] ≤ ℝ[x], null(A) = {x : Ax = 0} ≤ Fⁿ.',
      'U + W = {u + w} is the smallest subspace containing both U and W.']},
{id:'la-1.4', mod:'LA', week:1, pick:'I', title:'Span', src:'LA notes §1.4 (PDF p.12–14)', url:null,
 key:['span{v₁,…,vₙ} = all linear combinations a₁v₁+…+aₙvₙ; span ∅ = {0}.',
      'The span is the smallest subspace containing v₁,…,vₙ.',
      'b ∈ span{v₁,…,vₙ} ⟺ Ax = b is consistent, where A = (v₁ : … : vₙ).',
      'col(A) = span of the columns of A ≤ Fᵐ; b ∈ col(A) ⟺ Ax = b has a solution.']},
{id:'la-1.5', mod:'LA', week:1, pick:'I', title:'Linear independence', src:'LA notes §1.5 (PDF p.14–17)', url:null,
 key:['{v₁,…,vₙ} is linearly independent if a₁v₁+…+aₙvₙ = 0 forces a₁=…=aₙ=0 (only the trivial solution).',
      'Independent ⟺ every vector in the span has a UNIQUE expression as a linear combination.',
      'Linear Dependence Lemma: if S is dependent, some vⱼ ∈ span(S∖{vⱼ}) and removing it does not change the span.',
      'Columns of A are independent ⟺ null(A) = {0}.',
      'Any set containing 0 is dependent.']},
{id:'la-1.6', mod:'LA', week:1, pick:'I', title:'Bases', src:'LA notes §1.6 (PDF p.17–19)', url:null,
 key:['A basis is a linearly independent spanning set: every vector is a unique linear combination of basis vectors.',
      'Standard basis of Fⁿ: e₁,…,eₙ. Basis of ℝₙ[x]: {1, x, …, xⁿ}.',
      'Basis reduction theorem: any finite spanning set contains a basis.',
      'Finite dimensional = has a finite spanning set ⇒ has a basis. F[x] and F^∞ are infinite dimensional.']},
{id:'la-1.7', mod:'LA', week:1, pick:'C', title:'Dimension', src:'LA notes §1.7 (PDF p.19–22)', url:null,
 key:['Exchange Theorem: if {v₁,…,vᵣ} spans V and {w₁,…,wₙ} is independent, then n ≤ r.',
      'All bases of a finite-dimensional V have the same size, dim V. dim{0} = 0.',
      'dim Fⁿ = n, dim ℝₙ[x] = n+1, dim Matₘₓₙ = mn; ℂ has dimension 2 over ℝ but 1 over ℂ.',
      'Any independent set extends to a basis.',
      'In an n-dimensional space: more than n vectors ⇒ dependent; fewer than n ⇒ cannot span; exactly n ⇒ independent ⟺ spanning ⟺ basis.']},
// Week 2 — Linear Algebra
{id:'la-1.8', mod:'LA', week:2, pick:'I', title:'Column space, row space & rank', src:'LA notes §1.8 (PDF p.22–27)', url:null, key:[]},
{id:'la-1.9', mod:'LA', week:2, pick:'C', title:'Rank–Nullity Theorem for matrices', src:'LA notes §1.9 (PDF p.27–30)', url:null, key:[]},
{id:'la-2.1', mod:'LA', week:2, pick:'I', title:'Maps, matrix transformations & linear maps', src:'LA notes §2.1–2.3 (PDF p.31–35)', url:null, key:[]},
{id:'la-2.4', mod:'LA', week:2, pick:'I', title:'Isomorphisms', src:'LA notes §2.4 (PDF p.35–36)', url:null, key:[]},
{id:'la-2.5', mod:'LA', week:2, pick:'I', title:'Kernel & image of linear maps', src:'LA notes §2.5 (PDF p.36–38)', url:null, key:[]},
{id:'la-2.6', mod:'LA', week:2, pick:'C', title:'The matrix of a linear map', src:'LA notes §2.6 (PDF p.38–42)', url:null, key:[]},
{id:'la-2.7', mod:'LA', week:2, pick:'C', title:'Change of basis', src:'LA notes §2.7 (PDF p.42–43)', url:null, key:[]},
{id:'la-3.1', mod:'LA', week:2, pick:'I', title:'Real inner products & norms', src:'LA notes §3.1–3.2 (PDF p.44–47)', url:null, key:[]},
{id:'la-3.3', mod:'LA', week:2, pick:'I', title:'Orthogonality', src:'LA notes §3.3 (PDF p.47–49)', url:null, key:[]},
{id:'la-3.4', mod:'LA', week:2, pick:'C', title:'Gram–Schmidt orthonormalisation', src:'LA notes §3.4 (PDF p.49–54)', url:null, key:[]},
// Week 3 — Complex Analysis
{id:'ca-1', mod:'CA', week:3, pick:'I', title:'Complex numbers', src:'CA notes §1 (PDF p.4–9)', url:null, key:[]},
{id:'ca-2', mod:'CA', week:3, pick:'I', title:'The exponential function', src:'CA notes §2 (PDF p.10–11)', url:null, key:[]},
{id:'ca-3', mod:'CA', week:3, pick:'I', title:'Contours', src:'CA notes §3 (PDF p.12–17)', url:null, key:[]},
{id:'ca-4', mod:'CA', week:3, pick:'I', title:'Contour integration', src:'CA notes §4 (PDF p.18–22)', url:null, key:[]},
{id:'ca-5', mod:'CA', week:3, pick:'I', title:'Complex differentiation & Cauchy–Riemann', src:'CA notes §5 (PDF p.23–30)', url:null, key:[]},
{id:'ca-6', mod:'CA', week:3, pick:'I', title:'Fundamental Theorem of Calculus', src:'CA notes §6 (PDF p.31–33)', url:null, key:[]},
{id:'ca-7', mod:'CA', week:3, pick:'P', title:'Winding numbers', src:'CA notes §7 (PDF p.34–38)', url:null, key:[]},
// Week 4
{id:'ca-8', mod:'CA', week:4, pick:'I', title:'Closing contours', src:'CA notes §8 (PDF p.39–41)', url:null, key:[]},
{id:'ca-9', mod:'CA', week:4, pick:'C', title:'Cauchy’s Theorem', src:'CA notes §9 (PDF p.42–45)', url:null, key:[]},
{id:'ca-10', mod:'CA', week:4, pick:'C', title:'Cauchy’s Integral Formula', src:'CA notes §10 (PDF p.46–53)', url:null, key:[]},
{id:'ca-11', mod:'CA', week:4, pick:'I', title:'Higher derivatives', src:'CA notes §11 (PDF p.54)', url:null, key:[]},
{id:'ca-12', mod:'CA', week:4, pick:'P', title:'Liouville’s Theorem & Fundamental Theorem of Algebra', src:'CA notes §12 (PDF p.55–57)', url:null, key:[]},
{id:'ca-13', mod:'CA', week:4, pick:'C', title:'Power series & Laurent series', src:'CA notes §13 (PDF p.58–68)', url:null, key:[]},
// Week 5
{id:'ca-14', mod:'CA', week:5, pick:'C', title:'Singularities & residues', src:'CA notes §14 (PDF p.69–76)', url:null, key:[]},
{id:'ca-15', mod:'CA', week:5, pick:'C', title:'The Residue Theorem', src:'CA notes §15 (PDF p.77–82)', url:null, key:[]},
{id:'ca-16', mod:'CA', week:5, pick:'C', title:'Applications: real integrals & Jordan’s lemma', src:'CA notes §16 (PDF p.83–92)', url:null, key:[]},
{id:'ca-17', mod:'CA', week:5, pick:'I', title:'Fourier transforms (via residues)', src:'CA notes §17 (PDF p.93–94)', url:null, key:[]},
{id:'ca-18', mod:'CA', week:5, pick:'P', title:'Laplace transforms', src:'CA notes §18 (PDF p.95–97)', url:null, key:[]},

// ---------------------------------------------------------------- STREAM C
// Week 1 — Vector Calculus
{id:'vc-1.1', mod:'VC', week:1, pick:'I', title:'Vector review: dot & cross products', src:'VC notes §1.1', url:null,
 key:['‖u‖ = √(u_x²+u_y²+u_z²); unit vector û = u/‖u‖.',
      'a·b = a_x b_x + a_y b_y + a_z b_z = ‖a‖‖b‖cos θ; a·b = 0 ⟺ orthogonal; a·a = ‖a‖².',
      'a×b = det[[e_x,e_y,e_z],[a_x,a_y,a_z],[b_x,b_y,b_z]] is orthogonal to both a and b.',
      '‖a×b‖ = ‖a‖‖b‖|sin θ| = area of the parallelogram with sides a and b.']},
{id:'vc-1.2', mod:'VC', week:1, pick:'I', title:'Polar, cylindrical & spherical coordinates', src:'VC notes §1.2', url:null,
 key:['Plane polars (ρ,φ): x = ρcos φ, y = ρsin φ, 0 ≤ ρ < ∞, 0 ≤ φ < 2π.',
      'Cylindrical (ρ,φ,z): as plane polars plus z; ρ = √(x²+y²) is the distance from the z-axis.',
      'Spherical (r,θ,φ): x = r sinθ cosφ, y = r sinθ sinφ, z = r cosθ; r = ‖x‖, θ ∈ [0,π] measured from the z-axis.',
      'Basis vectors e_ρ, e_φ (and e_r, e_θ) are orthonormal but vary with position.']},
{id:'vc-1.3', mod:'VC', week:1, pick:'I', title:'Scalar & vector fields; gradient', src:'VC notes §1.3', url:null,
 key:['Scalar field f: ℝⁿ → ℝ (e.g. temperature). Vector field F: ℝⁿ → ℝᵐ, m > 1 (e.g. wind velocity).',
      '∂f/∂x: differentiate with respect to x holding the other variables constant.',
      '∇f = (∂f/∂x, ∂f/∂y, ∂f/∂z) — the gradient is a vector field.']},
{id:'vc-1.4', mod:'VC', week:1, pick:'I', title:'Double integrals', src:'VC notes §1.4', url:null,
 key:['∬_R f dA is evaluated by successive integration; the inner integral is done first.',
      'Non-constant limits may only appear on the inner integral(s).',
      'Changing the order of integration: redraw the region and re-derive the limits.',
      '∬_R 1 dA = area of R. In plane polars dA = ρ dρ dφ (don’t forget the ρ).']},
{id:'vc-1.5', mod:'VC', week:1, pick:'I', title:'Volume (triple) integrals', src:'VC notes §1.5', url:null,
 key:['∭_V f dV with dV = dx dy dz; ∭_V 1 dV = volume.',
      'Project V onto the xy-plane (region R), integrate z from z₁(x,y) to z₂(x,y) first, then over R.',
      'Cylindrical: dV = ρ dρ dφ dz. Spherical: dV = r² sinθ dr dθ dφ.']},
{id:'vc-2.1', mod:'VC', week:1, pick:'I', title:'Curves in 2D: parametrisation, tangent & length', src:'VC notes §2.1.1–2.1.4', url:null,
 key:['A curve C: t ↦ (x(t), y(t)), t₁ ≤ t ≤ t₂. Parametrisations are not unique.',
      'Eliminating t gives a geometric form y = f(x) or F(x,y) = 0 — this loses the start/end points and direction.',
      'Tangent v(t) = dx/dt = (x′(t), y′(t)); speed v(t) = ‖v(t)‖. Line element dx = v dt.',
      'Length L = ∫_{t₁}^{t₂} v(t) dt = ∫ √(x′² + y′²) dt, independent of the parametrisation.']},
{id:'vc-2.1.5', mod:'VC', week:1, pick:'P', title:'Arc-length & the natural parametrisation', src:'VC notes §2.1.5', url:null,
 key:['Arc-length s(t) = ∫_{t₁}^{t} v(t′) dt′, so ds/dt = v(t).',
      'Natural parametrisation: use s as the parameter (invert s(t)). Its tangent vector has unit length.']},
{id:'vc-2.2', mod:'VC', week:1, pick:'I', title:'Line integrals of scalar & vector fields', src:'VC notes §2.2', url:null,
 key:['Scalar field: ∫_C f ds = ∫_{t₁}^{t₂} f(x(t),y(t)) v(t) dt, where ds = v dt.',
      'Vector field: ∫_C F·dx = ∫_{t₁}^{t₂} F(x(t))·v(t) dt — a scalar; only the tangential component of F contributes.',
      '∮ denotes a closed curve. With f = 1 the scalar line integral gives the length.']},
{id:'vc-2.3', mod:'VC', week:1, pick:'I', title:'Curves in 3D', src:'VC notes §2.3', url:null,
 key:['Same ideas in 3D: C: t ↦ (x(t), y(t), z(t)), v = (x′, y′, z′), L = ∫ ‖v‖ dt.',
      'Helix (sin t, cos t, t): projects to the unit circle, v = (cos t, −sin t, 1), speed √2.']},
// Week 2 — Vector Calculus
{id:'vc-3.1', mod:'VC', week:2, pick:'I', title:'Representations of surfaces & normals', src:'VC notes §3.1–3.2', url:null, key:[]},
{id:'vc-3.3', mod:'VC', week:2, pick:'C', title:'Surface area & explicit geometric form', src:'VC notes §3.3–3.4', url:null, key:[]},
{id:'vc-3.5', mod:'VC', week:2, pick:'C', title:'Surface integrals', src:'VC notes §3.5', url:null, key:[]},
{id:'vc-4.1', mod:'VC', week:2, pick:'I', title:'Directional derivatives', src:'VC notes §4.1', url:null, key:[]},
{id:'vc-4.2', mod:'VC', week:2, pick:'I', title:'Divergence, curl & the Laplacian', src:'VC notes §4.2–4.4', url:null, key:[]},
{id:'vc-4.5', mod:'VC', week:2, pick:'I', title:'Conservative vector fields', src:'VC notes §4.5', url:null, key:[]},
// Week 3
{id:'vc-5.1', mod:'VC', week:3, pick:'C', title:'The Divergence Theorem', src:'VC notes §5.1', url:null, key:[]},
{id:'vc-5.2', mod:'VC', week:3, pick:'C', title:'Stokes’s Theorem', src:'VC notes §5.2', url:null, key:[]},
{id:'vc-5.3', mod:'VC', week:3, pick:'C', title:'Green’s Theorem', src:'VC notes §5.3', url:null, key:[]},
{id:'de-1a', mod:'DE', week:3, pick:'I', title:'Second-order ODEs & reduction of order', src:'DE notes Week 1 (PDF p.1–5)', url:null, key:[]},
{id:'de-1b', mod:'DE', week:3, pick:'I', title:'Differential operators & analytic functions', src:'DE notes Week 1 (PDF p.5–8)', url:null, key:[]},
{id:'de-2', mod:'DE', week:3, pick:'I', title:'Series solutions at ordinary points', src:'DE notes Week 2 (PDF p.9–15)', url:null, key:[]},
// Week 4
{id:'de-3', mod:'DE', week:4, pick:'C', title:'Regular singular points & Frobenius', src:'DE notes Week 3 (PDF p.16–21)', url:null, key:[]},
{id:'de-4', mod:'DE', week:4, pick:'C', title:'Bessel’s equation & series summary', src:'DE notes Week 4 (PDF p.22–28)', url:null, key:[]},
{id:'de-5', mod:'DE', week:4, pick:'C', title:'Boundary value problems', src:'DE notes Week 5 (PDF p.29–34)', url:null, key:[]},
{id:'de-6', mod:'DE', week:4, pick:'I', title:'Fourier series: Dirichlet, orthogonality, coefficients', src:'DE notes Week 6 (PDF p.35–43)', url:null, key:[]},
// Week 5
{id:'de-7a', mod:'DE', week:5, pick:'I', title:'Odd/even functions & half-range expansions', src:'DE notes Week 7 (PDF p.44–47)', url:null, key:[]},
{id:'de-7b', mod:'DE', week:5, pick:'C', title:'Fourier series for inhomogeneous ODEs', src:'DE notes Week 7 (PDF p.48–50)', url:null, key:[]},
{id:'de-8', mod:'DE', week:5, pick:'I', title:'Fourier transform: definition & properties', src:'DE notes Week 8 (PDF p.51–57)', url:null, key:[]},
{id:'de-9a', mod:'DE', week:5, pick:'C', title:'Derivative theorem & convolution', src:'DE notes Week 9 (PDF p.58–64)', url:null, key:[]},
{id:'de-9b', mod:'DE', week:5, pick:'I', title:'The Dirac delta function', src:'DE notes Week 9 (PDF p.65–67)', url:null, key:[]},
{id:'de-10', mod:'DE', week:5, pick:'C', title:'Impulse forcing & Green’s functions', src:'DE notes Week 10 (PDF p.68–76)', url:null, key:[]},
];

const SECTION_BY_ID = Object.fromEntries(SECTIONS.map(s => [s.id, s]));
const PICK_INFO = {
  I:{name:'Implement', color:'#34D399', desc:'Quick win — test first, read only what you miss'},
  C:{name:'Challenge', color:'#F59E0B', desc:'Hard & essential — learn today, prove it tomorrow'},
  P:{name:'Possible',  color:'#60A5FA', desc:'Skim — quick 3-question check'},
  K:{name:'Kill',      color:'#64748B', desc:'Skipped — non-examinable / low payoff'},
};

// Question bank — question files push into this.
const QUESTIONS = [];
